export const MESSAGE = {
  DB: {
    WRONG_ACCOUNT: "Incorrect database username or password",
    WRONG_SERVER: "Incorrect server name or connection string",
    FAILED_CONNECT: "Error connecting to Mongoose database",
  },
  USER: {
    LOGIN_SUCCESSFULLY: "Login user successfully",
    WRONG_ACCOUNT: "Incorrect email or password",
    EXIST: "User already exists",
    NOT_REGISTER: "Cannot register user",
    REGISTER_SUCCESSFULLY: "Login user successfully",
    NOT_REGISTER: "Cannot register user",
    GET_LIST_SUCCESSFULLY: "Get users successfully",
    GET_DETAIL_SUCCESSFULLY: "Get detail user successfully",
    USER_NAME_LEAST_5_CHARACTERS: "User name must be at least 5 characters",
    EMAIL_INCORRECT_FORMAT: "Email is incorrect format",
    PASS_LEAST_8_CHARACTERS: "Password must be at least 8 characters",
    PHONE_LEAST_8_CHARACTERS: "Phone number must be at least 8 characters",
    GET_LIST_FAILED: "Cannot get users",
    CANNOT_GET_DETAIL_USER: "Cannot get detail user",
    NOT_FIND_ID: "Cannot find user by id",
    CANNOT_UPDATE_USER: "Cannot update user",
    CANNOT_DELETE_USER: "Cannot delete user",
    CANNOT_CHECK_UNIQUE: "Cannot check user uniqueness",
    DELETED: "Deleted user successfully",
    CANNOT_DELETE_SELF: "Cannot delete self",
  },
  STUDENT: {
    GET_LIST_FAILED: "Cannot get students",
    GET_LIST_SUCCESSFULLY: "Get students successfully",
    GET_DETAIL_SUCCESSFULLY: "Get detail successfully",
    NOT_FIND_ID: "Cannot find student by id",
    UPDATED: "Updated student successfully",
    FAILED_UPDATE: "Cannot update student",
    CREATED: "Created student successfully",
    CREATED_FAKE: "Created fake student successfully",
    FAILED_CREATE: "Cannot create student",
  },
  BRAND: {
    EXIST: "Code or urlKey already exists",
    CREATED: "Created brand successfully",
    UPDATED: "Updated brand successfully",
    FAILED_CREATE: "Cannot create brand",
    FAILED_UPDATE: "Cannot update brand",
    GET_DETAIL_SUCCESSFULLY: "Get detail brand successfully",
    GET_LIST_SUCCESSFULLY: "Get brands successfully",
    GET_LIST_FAILED: "Cannot get brands",
    CANNOT_CHECK_UNIQUE: "Cannot check brand uniqueness",
    NOT_FIND_ID: "Cannot find brand by id",
    FAILED_DELETE: "Cannot delete brand",
    DELETED: "Deleted brand successfully",
  },
  TOKEN: {
    EXPIRED: "Token expired",
    INVALID: "Invalid token",
  },
  CATEGORY: {
    EXIST: "Category already exists",
    FAILED_CREATE: "Cannot create category",
    FAILED_UPDATE: "Cannot update category",
    GET_DETAIL_SUCCESSFULLY: "Get detail category successfully",
    GET_LIST_SUCCESSFULLY: "Get categories successfully",
    GET_LIST_FAILED: "Cannot get categories",
    CANNOT_CHECK_UNIQUE: "Cannot check category uniqueness",
    NOT_FIND_ID: "Cannot find category by id",
    FAILED_DELETE: "Cannot delete category",
    DELETED: "Deleted category successfully",
  },
  GET_DATA_SUCCESSFULLY: "Get data successfully",
  MIN_LENGTH: "must be at least 3 characters",
  PERMISSION_DENIED: "Permission denied",
  NOT_SUPPORTED: "not supported!!!",
};
