import { MESSAGE } from "../global/message.js";
import { print, OutputType } from "../helpers/print.js";

export default class Exception extends Error {
    static WRONG_DB_USERNAME_PASSWORD = MESSAGE.DB.WRONG_ACCOUNT;
    static WRONG_SERVER_NAME_DB = MESSAGE.DB.WRONG_SERVER;
    static WRONG_CONNECT_TO_MONGOOSE = MESSAGE.DB.FAILED_CONNECT;
    static USER_EXIST = MESSAGE.USER.EXIST;
    static CANNOT_REGISTER = MESSAGE.USER.NOT_REGISTER;
    static CANNOT_REGISTER_USER = MESSAGE.USER.NOT_REGISTER;
    static WRONG_EMAIL_OR_PASSWORD = MESSAGE.USER.WRONG_ACCOUNT;
    static USER_NAME_LEAST_5_CHARACTERS = MESSAGE.USER.USER_NAME_LEAST_5_CHARACTERS;
    static USER_EMAIL_INCORRECT_FORMAT = MESSAGE.USER.EMAIL_INCORRECT_FORMAT;
    static USER_PASS_LEAST_8_CHARACTERS = MESSAGE.USER.PASS_LEAST_8_CHARACTERS;
    static USER_PHONE_LEAST_8_CHARACTERS = MESSAGE.USER.PHONE_LEAST_8_CHARACTERS;
    static CANNOT_GET_USER = MESSAGE.USER.GET_LIST_FAILED;
    static CANNOT_GET_DETAIL_USER = MESSAGE.USER.CANNOT_GET_DETAIL_USER;
    static CANNOT_UPDATE_USER = MESSAGE.USER.CANNOT_UPDATE_USER;
    static CANNOT_DELETE_USER = MESSAGE.USER.CANNOT_DELETE_USER;
    static CANNOT_CREATE_STUDENT = MESSAGE.STUDENT.FAILED_CREATE;
    static CANNOT_UPDATE_STUDENT = MESSAGE.STUDENT.FAILED_UPDATE;
    static CANNOT_FIND_USER_BY_ID = MESSAGE.USER.NOT_FIND_ID;
    static CANNOT_FIND_STUDENT_BY_ID = MESSAGE.STUDENT.NOT_FIND_ID;
    static CANNOT_GET_STUDENT = MESSAGE.STUDENT.GET_LIST_FAILED;
    static CANNOT_CREATE_BRAND = MESSAGE.BRAND.FAILED_CREATE;
    static CANNOT_GET_BRAND = MESSAGE.BRAND.GET_LIST_FAILED;
    static CANNOT_UPDATE_BRAND = MESSAGE.BRAND.FAILED_UPDATE;
    static CANNOT_CHECK_BRAND_UNIQUE = MESSAGE.BRAND.CANNOT_CHECK_UNIQUE;
    static CANNOT_FIND_BRAND_BY_ID = MESSAGE.BRAND.NOT_FIND_ID;
    static CANNOT_DELETE_BRAND = MESSAGE.BRAND.FAILED_DELETE;
    static CANNOT_CHECK_USER_UNIQUE = MESSAGE.USER.CANNOT_CHECK_UNIQUE;
    static PERMISSION_DENIED = MESSAGE.PERMISSION_DENIED;
    static CANNOT_CREATE_CATEGORY = MESSAGE.CATEGORY.FAILED_CREATE;
    static CANNOT_GET_CATEGORY = MESSAGE.CATEGORY.GET_LIST_FAILED;
    static CANNOT_UPDATE_CATEGORY = MESSAGE.CATEGORY.FAILED_UPDATE;
    static CANNOT_FIND_CATEGORY_BY_ID = MESSAGE.CATEGORY.NOT_FIND_ID;
    static CANNOT_DELETE_CATEGORY = MESSAGE.CATEGORY.FAILED_DELETE;
    
    constructor(message, validationErrors={}) {
        super(message);
        print(message, OutputType.ERROR);
        this.validationErrors = validationErrors;
    }
}